### ISSUE TITLE
About the save_tf_record()

### ISSUE THREAD

**Issue by happyday521** [alexlee-gk/video_prediction#14]
Hi! Thanks for releasing the code! I am having some trouble preparing my own dataset. 
In function read_videos_and_save_tf_records（）:
![clipboard](https://user-images.githubusercontent.com/35884085/50535384-430c9f00-0b84-11e9-969e-356016bd8944.png)
I think one sequence corresponds to the frames of one video file（for example 1.avi） ，and  the function
save_tf_record（） save these frames to a .tfrecord file（e.g 1.tfrecord）.

However, in the function save_tf_record（）:
![clipboard1](https://user-images.githubusercontent.com/35884085/50535433-e362c380-0b84-11e9-8b10-7c4ab0638f4b.png)
It seems one sequence  corresponds to >= 1 video files. I am confused by it, 

Can you help me? Thanks!

**Comment by alexlee-gk** [comment]
That's right, the function `save_tf_record` can save multiple sequences corresponding to multiple files. However, this function was always just called with a single sequence.

This turned out to be quite inefficient. I have updated the master branch with several improvements, one of which is in the preprocessing of the KTH dataset. In the new version, you should see that `sequences_per_file=128` video sequences are saved in each tfrecord file.

Also, after you pull my changes, make sure to `pip install -r requirements.txt` again since there is one new dependency.

**Comment by happyday521** [comment]
Get it. Thanks！
