### ISSUE TITLE
eval image don't have action?

### ISSUE THREAD

**Issue by Sander-houqi** [alexlee-gk/video_prediction#7]
Hi Alex,

Thanks for releasing all the code. I am working on fitting a new dataset into your model. I resize the (height,width) to (256,256) which same as ucf101 datasets. I set context_frames equal to 2 in order to predict 8 frames with the model.
1. In the code, I find outputs['gen_images']  predict future frames in the generator and outputs['gen_inputs'] is the input clip. But in the tensorboard, in the step 0, it is intricate
that outputs['gen_images'] is as same as outputs['gen_inputs']，so could you give me some advice for the phenomenon?
2. when I use scripts/generate.py to predict future frames on my own model, the predict frames is same, don't have any action , it cause the gif images hold still .I debug the code ,and don't find any solutions, 
I look forward to your reply.

Do you have any good suggestion on this issue?

Thanks a lot.

Best,
Sander

**Comment by alexlee-gk** [comment]
1. `outputs['gen_inputs']` is *not* the input ground-truth clip. Instead, it is what the generator uses to condition for generating the next frame. It's \tilde{x}_{t-1} in Fig. 2 of the paper. Because of scheduled sampling, it varies what it is throughout training. At the beginning of training, the model does 1-step predictions, so `outputs['gen_inputs']` are the ground-truth frames. By the end of scheduled sampling, the model is auto-regressive, so `outputs['gen_inputs']` are the generated frames of the previous time-steps (except for the context frames, which are always the ground-truth frames). You shouldn't need to use these frames. They are for the conditional discriminators to use so that they are conditioned on the same frames as the generator.

2. You should figure out if the problem is with the visualization or with the model. For the latter, this could happen if you are using one of the models with a GAN. If the image discriminator is too strong, then one degenerate solution is to copy the first frame since that frame is always real. Of course, this shouldn't happen if the video discriminator is discriminative enough to detect that static frames are likely generated. For reference, you can also train a deterministic model and make sure the results are expected.

**Comment by Sander-houqi** [comment]
emmm,I mean during train step(0,100,etc), I turn out gif_freq to 100 in train.py, the result show gen_images is not different from ground-truth frames,that's make me confused.I originally expected the model excellent ,so I use the default setting in generate.py to test the model,but I get static frames. I use everything is  default except my own datasets, so why generate images is every save gif_freq step is same as the ground-truth frames?

**Comment by Sander-houqi** [comment]
Thanks,it solved after the training step extended.

**Comment by fatemehtd** [comment]
I am trying to train savp model on my dataset. The predicted future frames uing scripts/generate.py on my dataset are the same as each other. How can I solve this problem? How the training step is extended and why should it be the solution?
